### ISSUE TITLE
Formal verification wish list

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/morpho-blue#390]
List all the additional steps we could follow to improve the formal verification work:
- [x] **update to main**, notably taking into account the storage refactor (done in #373)
- [x] **fix timeouts** (mostly done in #442, see below for more)
- [x] refactor, file splitting and renaming (done in #461)
- [x] document the rules (done in #461)
- [x] document the whole verification (done in #465 and #538)
- [x] additional properties
    - [x] there are no accounts with non zero borrow and with zero collateral (done in #373, rule always collateralized)
    - [x] assuming no reverts due to external contracts, it's always possible to completely exit a borrow position, but it requires liquidity for a supply position (done for the most part in #451, except for the repayAll rule in #492)
    - [x] liveness properties about all the main functions (done in #467)
    - [x] roundtrip property with borrow-repay (done in #619)
    - [x] similar properties to the "owned/owed" properties of ExitLiquidity but for supply/borrow/supplyCollateral (see https://github.com/morpho-org/morpho-blue/pull/136#discussion_r1409030208, done in #623)
    - [x] a position gets healthier after a liquidation if its LTV was lower than 1 / LIF. This would ensure that the liquidation system has some breathing room to liquidate users before it leads to bad debt (done in #708)
    - [x] ~~check overflow reverting case on accrue interest~~ (abandoned)
    - [x] ~~check overflow reverting case on token~~ (abandoned)
    - [x] ~~check overflow reverting case on oracle~~ (abandoned)
- [x] improve rules
    - [x] `onlyLiquidateCanDecreaseSupplyRatio` can be more specific and require that the bad debt has been realized for the ratio to have decreased (new rule `liquidateWithoutBadDebtRealizationIncreasesSupplyRatio` written in #622)
    - [x] `userWithoutBorrowCannotLoseCollateral` can also state that only the liquidate function can make him lose collateral (new rule `userCannotLoseCollateralExceptLiquidate` written in https://github.com/morpho-org/morpho-blue/pull/461)
    - [x] supply-withdraw roundtrip with arbitrary withdraw (see https://github.com/morpho-org/morpho-blue/pull/345#discussion_r1297125249, done in #619)
    - [x] fix timeout on `liquidate` for the increase borrow ratio rule (done in #679)
    - [x] fix timeout on `repay` for the stay healthy rule (done in #679)
    - [x] fix timeout on `borrow` for the stay healthy rule (done in #679)
    - [x] fix timeout on `liquidate` for the stay healthy rule (done in #684)
- [x] ~~switch to compilation via IR~~ (not planned, see https://github.com/morpho-org/morpho-blue/pull/466#issuecomment-1822534061)
- [x] remove munging when no longer necessary
    - [x] remove munging on `Morpho.extSloads` (done in #458)
    - [x] check `MarketParamsLib.id` optimization (done in #491)
    - [x] remove munging on `MarketParamsLib.id` (done in #494)
- [x] switch back from `certora-cli-beta` when no longer necessary
- [x] robustness of the verification
    - [x] test with sanity (done in #599)
    - [x] test with mutations (done in #564) 

Previous invariant lists in #96 and #256.

**Comment by octavio12345300** [comment]
listo

**Comment by QGarchery** [comment]
Completed ! 🎉
