### ISSUE TITLE
Verify invariants about the protocol

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/morpho-blue#96]
The idea is to list the invariants about the protocols. This way we will remember to add them as forge invariants or certora invariants.

Current invariant list :
- [x] borrow is less than supply on a given market. It has to be checked with the liquidate function too. (done in #294)
- [x] for each market, on the singleton there is at least (totalSupply - totalBorrow) borrowable tokens and the whole collateral (done in #304)
- [x] only the markets with enabled LLTVs have non-zero data (done in #290)
- [x] only the markets with enabled IRMs have non-zero data (done in #290)
- [x] the ratio `shares / assets` on a market is increasing, except in liquidate (in progress in #341)
- [x]  sum_addresses(supplyShares(address)) = totalSupplyShare (done in #136)
- [x]  sum_addresses(borrowShares(address)) = totalBorrowShare (done in #136)
- [x]  sum_addresses(supplyShares(address).toAssetsDown()) <= totalSupply
This invariant is difficult to check because every user's owed assets can change at each interaction. Moreover, it can be deduced (modulo virtual assets and shares) given the 2 previous invariants by applying `toAssetsDown` on both sides. For these reasons, it has been replaced with the following property: a given user cannot withdraw more than `supplyShares(address).toAssetsDown()` assets. (done in #316)
- [x]  sum_addresses(borrowShares(address).toAssetsUp()) >= totalBorrow
For similar reasons as the invariant above, this invariant has been replaced with the following property: when repaying the whole position, a user is transfering more tokens than `borrowShares(address).toAssetsUp())` (done in #316)

(some of the invariants were taken from comments below, and put there for easier tracking)
